### PR TITLE
Add links to assemble koch v1.1 in China.

### PR DESCRIPTION
**Pull request by Felix-Zhenghao**
I live in China and have successfully assembled the robot. I have finished the configuration step and nothing bad happened. These links should be OK.

image

This closes issue https://github.com/jess-moss/koch-v1-1/issues/7.

### CODE REVIEW

**Comment by Felix-Zhenghao** [comment]
Again, many thanks to lerobot team. I like all lerobot stuff so much.

**Comment by Felix-Zhenghao** [comment]
I am also sure that the voltage reducer and control board are correct.

**Review by Cadene — APPROVED** [review]
View looks good!

https://github.com/jess-moss/koch-v1-1/blob/f734e97827587731ae283acf186641b96b9904b4/README.md

@jess-moss could you make sure the links are good before merging? Thanks!

**Comment by jess-moss** [comment]
Closes Issue #7

**Comment by jess-moss** [comment]
Thank you for finding these parts in China! @Felix-Zhenghao

**Pull request merged**
